// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: connect.proto

package connect_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Msg 消息结构体
// 对应源结构体:
//
//	type Msg struct {
//	   Ver       int    `json:"ver"`  // protocol version
//	   Operation int    `json:"op"`   // operation for request
//	   SeqId     string `json:"seq"`  // sequence number chosen by client
//	   Body      []byte `json:"body"` // binary body bytes
//	}
type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ver           int32                  `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`  // 协议版本
	Op            int32                  `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`    // 操作类型
	Seq           string                 `protobuf:"bytes,3,opt,name=seq,proto3" json:"seq,omitempty"`   // 客户端选择的序列号
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // 二进制消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetVer() int32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *Msg) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *Msg) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *Msg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// PushMsgRequest 推送给单个用户的消息请求
// 对应源结构体:
//
//	type PushMsgRequest struct {
//	  UserId int
//	  Msg    Msg
//	}
type PushMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 目标用户ID
	Msg           *Msg                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                      // 要推送的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgRequest) Reset() {
	*x = PushMsgRequest{}
	mi := &file_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgRequest) ProtoMessage() {}

func (x *PushMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgRequest.ProtoReflect.Descriptor instead.
func (*PushMsgRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{1}
}

func (x *PushMsgRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushMsgRequest) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

// PushRoomMsgRequest 推送给房间的消息请求
// 对应源结构体:
//
//	type PushRoomMsgRequest struct {
//	  RoomId int
//	  Msg    Msg
//	}
type PushRoomMsgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 目标房间ID
	Msg           *Msg                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                      // 要推送的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomMsgRequest) Reset() {
	*x = PushRoomMsgRequest{}
	mi := &file_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomMsgRequest) ProtoMessage() {}

func (x *PushRoomMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomMsgRequest.ProtoReflect.Descriptor instead.
func (*PushRoomMsgRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{2}
}

func (x *PushRoomMsgRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PushRoomMsgRequest) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

// PushRoomCountRequest 更新房间用户计数请求
// 对应源结构体:
//
//	type PushRoomCountRequest struct {
//	  RoomId int
//	  Count  int
//	}
type PushRoomCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // 目标房间ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 用户数量计数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomCountRequest) Reset() {
	*x = PushRoomCountRequest{}
	mi := &file_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomCountRequest) ProtoMessage() {}

func (x *PushRoomCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomCountRequest.ProtoReflect.Descriptor instead.
func (*PushRoomCountRequest) Descriptor() ([]byte, []int) {
	return file_connect_proto_rawDescGZIP(), []int{3}
}

func (x *PushRoomCountRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *PushRoomCountRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_connect_proto protoreflect.FileDescriptor

const file_connect_proto_rawDesc = "" +
	"\n" +
	"\rconnect.proto\x12\n" +
	"connect_pb\"M\n" +
	"\x03Msg\x12\x10\n" +
	"\x03ver\x18\x01 \x01(\x05R\x03ver\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\x05R\x02op\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\tR\x03seq\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"L\n" +
	"\x0ePushMsgRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12!\n" +
	"\x03msg\x18\x02 \x01(\v2\x0f.connect_pb.MsgR\x03msg\"P\n" +
	"\x12PushRoomMsgRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12!\n" +
	"\x03msg\x18\x02 \x01(\v2\x0f.connect_pb.MsgR\x03msg\"E\n" +
	"\x14PushRoomCountRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x05R\x06roomId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05countB\x18Z\x16yoyichat/pb/connect_pbb\x06proto3"

var (
	file_connect_proto_rawDescOnce sync.Once
	file_connect_proto_rawDescData []byte
)

func file_connect_proto_rawDescGZIP() []byte {
	file_connect_proto_rawDescOnce.Do(func() {
		file_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)))
	})
	return file_connect_proto_rawDescData
}

var file_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_connect_proto_goTypes = []any{
	(*Msg)(nil),                  // 0: connect_pb.Msg
	(*PushMsgRequest)(nil),       // 1: connect_pb.PushMsgRequest
	(*PushRoomMsgRequest)(nil),   // 2: connect_pb.PushRoomMsgRequest
	(*PushRoomCountRequest)(nil), // 3: connect_pb.PushRoomCountRequest
}
var file_connect_proto_depIdxs = []int32{
	0, // 0: connect_pb.PushMsgRequest.msg:type_name -> connect_pb.Msg
	0, // 1: connect_pb.PushRoomMsgRequest.msg:type_name -> connect_pb.Msg
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_connect_proto_init() }
func file_connect_proto_init() {
	if File_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_proto_rawDesc), len(file_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_proto_goTypes,
		DependencyIndexes: file_connect_proto_depIdxs,
		MessageInfos:      file_connect_proto_msgTypes,
	}.Build()
	File_connect_proto = out.File
	file_connect_proto_goTypes = nil
	file_connect_proto_depIdxs = nil
}
