[common-etcd]
host = "127.0.0.1:2379" # etcd 服务地址
basePath = "/gochat_srv" # etcd 根路径
serverPathLogic = "LogicRpc" # 逻辑层 注册路径
serverPathConnect = "ConnectRpc" # 连接层 注册路径
userName = "" # 用户名 (空表示无认证)
password = "" # 密码 (空表示无认证)
connectionTimeout = 5 # 连接超时(秒)

[common-redis]
redisAddress = "127.0.0.1:6379" # redis 地址
redisPassword = "" # redis 密码 空表示无认证
db = 0 # redis 数据库编号